sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t ozekidesu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ozekidesu/react-test npm test

after_success:
  - docker build -t ozekidesu/multi-client ./client # Don't have to specify the docker filename as Dockerfile is the default
  - docker build -t ozekidesu/multi-nginx ./nginx 
  - docker build -t ozekidesu/multi-server ./server
  - docker build -t ozekidesu/multi-worker ./worker

# Log in to the docker CLI
# Configure username and password variables in Travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push ozekidesu/multi-client
  - docker push ozekidesu/multi-nginx
  - docker push ozekidesu/multi-server
  - docker push ozekidesu/multi-worker